print("Complete Name: Ronald Franco Galendez")
print("Course: Computer Science")
print("Section: CS1D")
print("Age: 19")
print("Birthday: Sept 5, 2004")
print("Complete Home Address: Lapaz 1, Lapasan, CDOC")
print('--------')
print("Complete Name: Rafi Sailal Panandigan")
print("Course: Computer Science")
print("Section: CS1D")
print("Age: 20")
print("Birthday: March 18 , 2003 ")
print("Complete Home Address: The Loop Cogon, CDO")
print('--------')
print("Complete Name: Jayson R Soriano")
print("Course: Computer Science")
print("Section: CS1D")
print("Age: 19")
print("Birthday: September 02 , 2004 ")
print("Complete Home Address: Block 8,Lot 39, Mindanao Homes, Pagatpat, CDO")

